<Project>
  <!-- single source of truth for version + identity, per manimal mod conventions -->
  <PropertyGroup>
    <ModVersion>0.1.8</ModVersion>
    <ModGuid>com.manimal.terminal</ModGuid>
    <ModUsername>Manimal</ModUsername>
    <ModDisplayName>Terminal</ModDisplayName>
    <SPTPath>D:\SPTFreshDev</SPTPath>
    <FikaPath>D:\SPTDevFika</FikaPath>
  </PropertyGroup>
</Project>
